name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./ https://edward-parcial1.surge.sh

        